### ISSUE TITLE
Erro ao instalar scrip

### ISSUE THREAD

**Issue by Glecson** [celostad/PetLivre#1]
![FB_IMG_1607625531730](https://user-images.githubusercontent.com/75261793/101855547-f84e7c80-3b39-11eb-8e7a-51858cc6940a.jpg)
Estou com esse erro

**Comment by celostad** [comment]
> ![FB_IMG_1607625531730](https://user-images.githubusercontent.com/75261793/101855547-f84e7c80-3b39-11eb-8e7a-51858cc6940a.jpg) Estou com esse erro

Olá Glecson, desculpe a demora na resposta.
Estou atualizando esse sistema para o framework Laravel, em breve com mais novidades.

Abraços
